version: '3.8'

services:
  app:
    env_file:
      - .env
    build:
      context: .
      args:
        GENERATION_DATA_SIZE: ${GENERATION_DATA_SIZE}
    ports:
      - "8080:8080"
    links:
      - postgresql

  postgresql:
    build:
      context: init_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    env_file:
      - .env
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/postgres
      - --username=postgres
      - --password=postgres
      - update-to-tag
      - ${MIGRATIONS_VERSION}
    volumes:
      - ./migrations:/liquibase/changelog