app:
  generation-data-size: ${GENERATION_DATA_SIZE}

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  application:
    name: itmo-db-lab-2
  datasource:
    url: jdbc:postgresql://postgresql:5432/postgres?stringtype=unspecified
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
