app:
  generation-data-size: ${GENERATION_DATA_SIZE}

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true
        format_sql: true
    database-platform:
      org.hibernate.dialect.MySQLDialect
  application:
    name: itmo-db-lab-2
  datasource:
    url: jdbc:postgresql://haproxy:5000/postgres?stringtype=unspecified
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
